### ISSUE TITLE
p2sh error when sweeping private keys into BTCP electrum wallet.

### ISSUE THREAD

**Issue by ericdzen** [BTCPrivate/electrum-btcp#13]
### Describe the issue
When I try to sweep my private keys over to the BTCP wallet I am getting a p2sh error.

#### If so, please list the steps to reproduce below:
1. Export private keys from ZCL wallet.
2. Install BTCP electrum wallet
3. Hover the Wallets menu options, go down to private keys, and select the sweep option.
4. Paste all private keys into the text box and press next.
5. p2sh error displays in a modal.
*Note - During the snapshot I was using a 2fa ZCL wallet and switched that wallet to a multi-signature wallet post fork.

### Expected behaviour
Private keys can be swept into the BTCP wallet without running into a p2sh error.

### Actual behaviour + errors
p2sh error occurs when trying to sweeps keys into BTCP electrum wallet.

### The version of Bitcoin Private you were using:
Version P!1.0.0
### Machine specs:
- OS name + version: Windows 10 Home (Version: 1709)
- CPU: 2.4GHz
- RAM: 6.00 GB

**Comment by ch4ot1c** [comment]
Is this wallet zcl multisig (from t3)? Try New->Multi-Sig Wallet for setup.

**Comment by ericdzen** [comment]
Yeah, the ZCL wallet is multisig with t3 addresses. I followed these steps to convert the 2fa ZCL wallet into a  multisig: https://github.com/z-classic/electrum-zcl/issues/44. When I tried to create a BTCP multisig wallet from my ZCL seed it was wouldn't accept it as it was still labeled as a 2fa seed and the next button was grayed out.

This did however give me an idea. I followed the same steps in Zclassic issue 44 I linked above and was able to use my ZCL wallet xprv and xpub addresses while creating a BTCP multisig to transfer my Zclassic private addresses. 

**Resolution to issue**
1. Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets. Open your Zclassic mutisig wallet file with Notepad (This wallet should have been setup with “From 3 co-signers” on the first slider. Select “Require 2 signatures").
2. You will need to gather the 2 private keys and one public key. To find this easily, press “CTRL+F” and search for “xprv”. Copy the 2 “xprv” values as well as the last “xpub” value. You will need these in a later step.
3. Create a new BTCP “Multi-signature wallet”. Select “From 3 co-signers” on the first slider. Select “Require 2 signatures” on the second slider.
4. To add the first co-signer, click “Use public or private keys”. Enter the first xprv key in this box.
5. Add the second co-signer via a private key also.
6. Add the third co-signer with the public key. Complete the set-up by adding a password if desired. 
7. Your BTCP should now be available in this new BTCP multisig wallet.

**Comment by AH1111** [comment]
The wallet we are having issues with is the electrum BTC wallet

**Comment by AH1111** [comment]
We have already done the electrum zcl wallet, and everything worked fine.

**Comment by cezarvpaes** [comment]
I have 2fa wallet type zcl, cant import the private keys, same error, cant find xpub and xprv on wallet file.

**Comment by ericdzen** [comment]
If your wallet is password protected or if 2fa is enabled then the xpub and xprv values won't show up in wallet file. Try the steps below to get the xpub and xprv values.
1. Create a new standard wallet and restore the 2FA wallet using your "seed" codes. DO NOT password protect this wallet.
2. Disable the 2FA feature when presented with the option.
3. Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets. Open the new standard wallet file with Notepad.

**Comment by AH1111** [comment]
OK, we did exactly as above, we restored the Electrum BTC wallet using the seed, we diasbled 2FA and did not password protect it.  When we go to the address to get the private key it is still the same key and format p2sh.....we still get the same error when trying to sweep it into the btcp wallet.  I really appreciate your help but are we doing something wrong again....I thought we did everything as you said

**Comment by Ayms** [comment]
https://github.com/BTCPrivate/BitcoinPrivate/issues/124

**Comment by AH1111** [comment]
So I'm not a programmer.  I'm completely confused about all the language.
Shouldn't this p2sh issue be easier to figure out for the average BTC
holder looking to claim BTCP?  Or is it easy and I'm just missing something?

**Comment by ch4ot1c** [comment]
#11

**Comment by Horeas** [comment]
https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/issues/31
