### ISSUE TITLE
BTCP Electrum Wallet 1.0.0 - Not Connecting? 

### ISSUE THREAD

**Issue by throwawaypdx** [BTCPrivate/electrum-btcp#15]
Just downloaded, ran, followed all instructions... Have been unable to get the wallet to connect for several hours. What am I missing?

Thanks in advance for any suggestions!

**Comment by xdemocle** [comment]
Same issue for me. I just restarted the electrum app and then it connected successfully.

**Comment by shoaibshuja5** [comment]
Thanks @xdemocle ....It worked for me as well.

**Comment by adnome** [comment]
I have restarted the app numerous times, left it running overnight, reinstalled/redownloaded, checked and unchecked all the boxes, and still can't get it to connect. I am not running a firewall and can ping electrum.btcprivate.org successfully. What else can I try to get this to connect?

**Comment by ch4ot1c** [comment]
A spinner should solve this.

**Comment by throwawaypdx** [comment]
This issue spontaneously resolved itself, got it working!

Thanks for the helpful comments, everyone. Cheers

**Comment by mkedzierski** [comment]
<img width="831" alt="zrzut ekranu 2018-03-05 o 00 03 34" src="https://user-images.githubusercontent.com/37053851/36953072-d682cb96-2017-11e8-869d-10317bcd1d70.png">


MacOsSierra not working not connected ;(

**Comment by mkedzierski** [comment]
Block explo
<img width="831" alt="zrzut ekranu 2018-03-05 o 01 56 20" src="https://user-images.githubusercontent.com/37053851/36953120-730331a4-2018-11e8-9cd5-586b6529fede.png">
