### ISSUE TITLE
Sweep Private Keys function Grayed out, can't click button. 

### ISSUE THREAD

**Issue by seanbebliss** [BTCPrivate/electrum-btcp#17]
The sweep private keys function is not working on my wallet. I've tried copy paste, import jason, import csv... the "sweep" button never activates. No click allowed.

**Comment by NatalieJRB** [comment]
Same issue

**Comment by syndrael** [comment]
Same for me. If i'm not wrong, i can't claim my BTCP from ZCL fork.
If it may help you, i'm a debian Stretch 64 bits. Wallet installed from scratch with Source.tgz
Regards

**Comment by seanbebliss** [comment]
The problem is us, not the program (but it does seem ridiculous that it doesn't accept electra csv/jason exports as functional imports). The private key you put in needs to be just one of the many you are given. See this page for an example of what the key looks like, it should not be longer than the one shown in the picture. https://bitcoinelectrum.com/sweeping-your-private-keys-into-electrum/ 

When I took just one address like this from my ZCL wallet it activated the sweep button so I could click it and I now have my BTCP. :)
