### ISSUE TITLE
Electrum-btcp app quit unexpectedly on my imac - cannot open it - pls advise

### ISSUE THREAD

**Issue by anthonytahara** [BTCPrivate/electrum-btcp#18]

**Comment by twalsh389** [comment]
i cant open either wallets on mac

**Comment by ootisra** [comment]
me too please help

**Comment by MayaMax18** [comment]
Hi,
I'm also can't get either wallet to work, Mac, using El Capitan. Just keeps quiting....Help Please!

**Comment by Angelgaboo** [comment]
Please I'm having this same issue. i need help to get this fixed.

**Comment by KimboKastekniv** [comment]
Same error with Yosemite OSX

**Comment by ch4ot1c** [comment]
El Capitan and Yosemite OSX have been noted as not yet supported - thank you for catching this. We will work on it this week. Closing - reopen if you have a more specific issue.
