### ISSUE TITLE
"Next" button disabled when trying to add private key

### ISSUE THREAD

**Issue by aloth** [BTCPrivate/electrum-btcp#21]
After entering the private key (originally created as ZCL paper wallet), the "Next" button remains grey and cannot be clicked.

Is there any workaround available?

![btcp wallet](https://user-images.githubusercontent.com/12732979/36948059-237f045c-1fd5-11e8-88f8-182efcd60a6b.png)

**Comment by mishu-** [comment]
Same thing on:
![image](https://user-images.githubusercontent.com/611429/36950192-1151500c-1ffb-11e8-87ce-a366bc4745a6.png)

**Comment by ch4ot1c** [comment]
hm - what is the corresponding zcl address type? t1 or t3?

**Comment by mikemiyao** [comment]
I have the same problem.  Does anyone know the work around?

**Comment by aloth** [comment]
Mine is a t1 address and was originally created here: https://zclassicpaperwallet.com/

**Comment by nickt233** [comment]
I am having the same problem when I'm trying to import my keys from my zcl electrum wallet..any suggestions?
