### ISSUE TITLE
Cannot open Electrum Win File

### ISSUE THREAD

**Issue by NatalieJRB** [BTCPrivate/electrum-btcp#22]
I had the electrum wallet holding ZCL. I have tried to download and open the electrum windows file for BTCP. The file downloads to my computer and when I choose "run" there is a flash across my screen for a second and then nothing. Have tried restarting, redownloading. The file tries to open in internet explorer.
Please advise.
Thank you!

**Comment by marleygra** [comment]
having the same issue

**Comment by NatalieJRB** [comment]
@marleygra I got a 7-zip extractor and was able to open the file. Try that
