### ISSUE TITLE
date not verified

### ISSUE THREAD

**Issue by macankur** [BTCPrivate/electrum-btcp#24]
installed the electrum btcp wallet on my macbook, and got all btcp coins as well. but the date shows "not verified" how can i fix this?
![screen shot 2018-03-05 at 2 13 50 am](https://user-images.githubusercontent.com/37047084/36950361-e2b517a4-201a-11e8-8647-cb7ed2c87cb2.png)

**Comment by madmack1** [comment]
I also have this issue on ubuntu.  
How do i fix it?

EDIT. Issue fixed. Just waited a while longer

**Comment by IceAge0121** [comment]
Hello, could you guys try this: https://support.btcprivate.org/464851-Transactions-Are-Unconfirmed-For-HoursDays

You'll have to modify the procedure according to OS and BTCP wallet.

**Comment by shoaibshuja5** [comment]
Who are facing Not Connected, Not verified issue can download this Header File and replace it in btcp wallet folder. Its updated till 280k blocks
https://goo.gl/buAhjE

**Comment by ch4ot1c** [comment]
Just wait! We will have a faster header download coming with the next version.
