### ISSUE TITLE
Using Seed Names from ZClassic Wallet

### ISSUE THREAD

**Issue by stellorgold** [BTCPrivate/electrum-btcp#25]
I launched the BTCP Electrum Wallet and used the seed names from my ZClassic Electrum Wallet. I had read that this would work !
I have been credited correctly with BTCP but they are all unverified and have been for 14 hours.
The wallet synced ok but still not verified ?

Any help on this would be much appreciated.

**Comment by IceAge0121** [comment]
Hello, could you try this: https://support.btcprivate.org/464851-Transactions-Are-Unconfirmed-For-HoursDays

You'll need to modify for sure with Electrum, but the procedure should be very similar.

**Comment by stellorgold** [comment]
That worked like a charm, thanks IceAge0121 for your help...
