### ISSUE TITLE
XPRV keys needed

### ISSUE THREAD

**Issue by AH1111** [BTCPrivate/electrum-btcp#28]
Trying to set up a multisig wallet using xpub key and xprv keys.....can't find the xprv keys at all.  I hit control F and search xprv and see this.  I've been dealing with the P2sh error issue by going with multisig wallet.
Please help so we can claim all of our BTCP.
![image](https://user-images.githubusercontent.com/36057398/36953592-fddeec16-1fe9-11e8-8ed9-6898aad7ed2b.png)

**Comment by ch4ot1c** [comment]
Users can apply their ZCL / BTC wallet xprv and xpub addresses while creating a BTCP multisig:

- Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets. Open your BTC mutisig wallet file with Notepad (This wallet should have been setup with “From 3 co-signers” on the first slider. Select “Require 2 signatures").
- You will need to gather the 2 private keys and one public key. To find this easily, press “CTRL+F” and search for “xprv”. Copy the 2 “xprv” values as well as the last “xpub” value. You will need these in a later step.
- Create a new BTCP “Multi-signature wallet”. Select “From 3 co-signers” on the first slider. Select “Require 2 signatures” on the second slider.
To add the first co-signer, click “Use public or private keys”. Enter the first xprv key in this box.
- Add the second co-signer via a private key also.
- Add the third co-signer with the public key. Complete the set-up by adding a password if desired.
- Your BTCP should now be available in this new BTCP multisig wallet.

**Comment by AH1111** [comment]
Problem solved.
Close this ticket

**Comment by AH1111** [comment]
Problem solved, close the ticket.  It was so easy..........no need for the
multisig wallet, we just created a new wallet using the seed......can't
believe how easy it was.  And we spent 3 days on this......exhaustion can
cause me to not think clearly
