### ISSUE TITLE
Electrum BTCP worked fine the first time I opened it, after closing it wont open again

### ISSUE THREAD

**Issue by valemany** [BTCPrivate/electrum-btcp#29]
I am using macOS sierra version 10.12.6

**Comment by KaboomFox** [comment]
Did you copy the application into your Applications directory?

**Comment by ootisra** [comment]
Yes I copied the application on my Applications Directory, and I have tried
several things, like re-download the zip file, deleting all the caches,
closing all the applications, rebooting the mac. really dont know what to
do now.
Thank you

**Comment by valemany** [comment]
I did.

**Comment by valemany** [comment]
Restarting the machine solved the issue. Will close this ticket for now. Thanks for the quick response.
