### ISSUE TITLE
BTCP electrun wallet not getting connections

### ISSUE THREAD

**Issue by Damuammu** [BTCPrivate/electrum-btcp#31]
Dear team,

Iam using electrum wallet for zcl, xvg and btcp. but for btcp connection is not getting, it says offline all time. Below are images for your investigation. Please help me.
https://user-images.githubusercontent.com/749993/36962472-b4fd8682-208a-11e8-9141-74c370c561ad.png
![image](https://user-images.githubusercontent.com/749993/36963399-fcfb1258-208d-11e8-93a4-8b352097084f.png)
![image](https://user-images.githubusercontent.com/749993/36963420-0d4e5818-208e-11e8-9015-4b1d3c4b2b7a.png)
![image](https://user-images.githubusercontent.com/749993/36963433-1a98d246-208e-11e8-8d1c-ad02f7527345.png)

Thanks
Damodar

**Comment by efazati** [comment]
me too, i have same issue. electrum-btcp not connected. is electrum.btcprivate.org:5222 correct?

**Comment by DurtMcGurt** [comment]
Similar issue.  I Installed this to sweep my ZCL address and claim BTCP but sweep cannot reach server and wallet says "not connected" in bottom left.  I had similar issues with the ZCL wallet but it did connect eventually and functioned enough to get the ZCL in and out of the wallet for the fork.

**Comment by ch4ot1c** [comment]
electrum.btcprivate.org:5222 is correct; it is several electrum servers behind a load balancer. If you're patient it should connect.

**Comment by dogking08** [comment]
still not working

**Comment by gr33k** [comment]
read somewhere on twitter to use electrum3.btcprivate.org:5222 and still no dice - Does anyone know how to get this thing to connect or are we doomed to using main wallet (all I want to do is swap my coins and send them off to coinomi and never worry about this crap again lol)

Oh and if the load balancer takes this long - I recommend a better one. If Header sync is taking forever - I recommend some status message to indicate progress...
