### ISSUE TITLE
Windows Tablet - download not working

### ISSUE THREAD

**Issue by Jezebell86** [BTCPrivate/electrum-btcp#32]
Have downloaded the file - it opens as a .win file though and then just opens a windows browser....
Running Windows 10 Pro on a Surface...clearly missing something! HALPPPP :)

**Comment by frayala2** [comment]
i was having the same issue with my laptop... once i got the 7z app not 7zip it worked. again i was on a lap top not surface but running windows 10. check the thread that says.."Post windows download as ZIP instead of 7z"

**Comment by ch4ot1c** [comment]
7zip; working toward zip once we get signing certificate.
