### ISSUE TITLE
Sweeping Bitcoin private keys is not working(p2sh)

### ISSUE THREAD

**Issue by vummuti** [BTCPrivate/electrum-btcp#37]
When I am trying to import my Bitcoin private keys, a small window with "p2sh" pops and nothing happens after that. I am able to import my ZCL private keys without any issues. 
![electrum_errorimage](https://user-images.githubusercontent.com/26492584/37008510-ff468794-20a7-11e8-8b4a-d85aabd25076.png)

**Comment by AH1111** [comment]
We had the same issue when trying to sweep the keys from the electrum BTC wallet.  Unfortunately my wife created a 2fa wallet password protected......that seems to be the issue.  We have the xpub keys from the 2fa wallet but can't seem to find the xprv keys from the original 2fa wallet (electrum BTC).....we were trying to restore/new wallet using the xprv and xpub keys but we can't find the xprv keys to do so.....every time we open a ticket, the response doesn't help and the ticket is closed as though it did.....How can we rightfully claim our btcp if we can't get an answer......I donated 1BTC to the developers prefork and I need help please.

**Comment by AH1111** [comment]
Use the seed

**Comment by ch4ot1c** [comment]
Nice! Thank you for the comment and Sorry for the trouble.

**Comment by vummuti** [comment]
Using the seed worked. Thanks for the help
