### ISSUE TITLE
 BTCP Electrum 1.0 changed addresses

### ISSUE THREAD

**Issue by javierea** [BTCPrivate/electrum-btcp#39]
Sorry for my ignorance, already searched and didn´t find this:
My BTCP address changed today, same amount of coins... I still get coins sent to my "yesterday" address ? Will I lose what i mined and wasn´t send before address changed?

**Comment by ch4ot1c** [comment]
Private key from ZCL / BTC reflects a BTCP address; indeed it is a different address.
