### ISSUE TITLE
BTCPrivate electrum wallet download wont unzip

### ISSUE THREAD

**Issue by dogmanosu** [BTCPrivate/electrum-btcp#46]
windows 10
keeps asking me what file I want to use to open it, then give me choices from Adobe, on down the list.  
I don't know what to choose or if I need to download something else.
Thank you for your time.

**Comment by fafrd** [comment]
The program is in a .7z file. You can use 7-Zip to open it: https://www.7-zip.org/

**Comment by dogmanosu** [comment]
Thank you.  I went to download from 7-zip.org and a pop up from user
account control asked if I want to allow this app from unknown publisher
make changes to your device?
Is this typical?

**Comment by fafrd** [comment]
That's normal, I accepted this and it worked fine for me. (This happens with any Windows installer that doesn't pay for a code signing certificate.)

If you are really paranoid, you could install 7-zip on a separate computer, or use the program WinZip instead
