### ISSUE TITLE
BTCP wallet won't remember password on MAC ?

### ISSUE THREAD

**Issue by ForKHELP1989** [BTCPrivate/electrum-btcp#47]
The BTCP wallet won't remember password on MAC ?

I have deleted and reinstalled all wallets starting with the BTCP electrum wallet , then the BTCP full node desktop and  then the BTCP testNET  wallet which seemed to be the only 1 that would let me make a password.

ALL of them did not work, then installed the correct JAVA and UPDATED my MAC OS to Sierra version.

Now the wallet loads but it doesn't remember my password to log in ? ? please help someone.. this is really frustrating and annoying and a huge disappointment in making this so called FORK an easy process has been a complete nightmare..

**Comment by ch4ot1c** [comment]
You definitely don't want to be on the testnet wallet; just use the latest.

Your 'password' is an optional, additional security layer that you can set at the end. It does not 'automatically save' in the text box. Fundamentally, your Seed Words / unencrypted wallet.dat file are what you need to keep safe. The password is so random people using your computer can't compromise your wallet.

**Comment by ForKHELP1989** [comment]
So how do i log into to get my BTCP because it asks for password every time ??

**Comment by ForKHELP1989** [comment]
how can i log in to get my BTCP ? because it asks for password every time i
open the wallet ?

**Comment by ForKHELP1989** [comment]
hello ?

the BTCP doesn't remember my password ? how can i log in ?

**Comment by ForKHELP1989** [comment]
The BTCP wallet doesn't remember my password to log in ?

still need to claim my BTCP... how can i log in or claim my BTCP really annoying...
