### ISSUE TITLE
Lost BTCP?

### ISSUE THREAD

**Issue by ccshapiro** [BTCPrivate/electrum-btcp#48]
On March 8th, 2018, I transferred my keys from my ZCL electrum wallet to my new BTCP electrum wallet. All
my BTCP were there after my 1:1 ZCL:BTCP fork. On March 13th,2018 I went in to my BTCP electrum wallet and it was empty. No transaction history in either wallet that the transfer ever took place. Can someone help?!?!

**Comment by ch4ot1c** [comment]
I assume by 'transferred' you mean imported. Get the latest release and try importing them again, and post a screenshot of what you see both there and in electrum-zcl.

**Comment by ccshapiro** [comment]
Thank you for your response. I was able to redo the process and import my keys to the Bitcoin private wallet and I have all of them where they belong. Thanks again.

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 16, 2018 at 10:39 AM, Jon Layton<notifications@github.com> wrote:   
I assume by 'transferred' you mean imported. Get the latest release and try importing them again, and post a screenshot of what you see both there and in electrum-zcl.

**Comment by ch4ot1c** [comment]
Yay!
