### ISSUE TITLE
can't ACCESS BTCP wallet .... 

### ISSUE THREAD

**Issue by ForKHELP1989** [BTCPrivate/electrum-btcp#51]
originally downloaded TESTNET WALLET which wouldn't work.. 

then reinstalled mac os beta electrum wallet , updated my mac to OS sierra and installed correct java.

now the wallet loads but doesn't remember my password when i log in....

this is really frustrating still can't get my BTCP and i have the private keys ready...

**Comment by ch4ot1c** [comment]
It does not remember the password. The password is optional and for your added security.

If you have those private keys, you can simply make a new wallet (type a new wallet name) and import them all.

**Comment by ForKHELP1989** [comment]
How do i make a new wallet ? Can you send instructions please thanks
