### ISSUE TITLE
Ledger Nano S - Invalid sequence

### ISSUE THREAD

**Issue by florianfink** [BTCPrivate/electrum-btcp#55]
The issue described here doesn't seem to be fixed yet in electrum-btcp:

https://github.com/spesmilo/electrum/issues/4191

**Comment by Artanisx** [comment]
Same here.
I get "Invalid Sequence" and can't go forward with the wallet setup (my Ledger Nano S is updated to the latest firmware, the Bitcoin private app is installed and ready).

**Comment by sulmone** [comment]
Look at the last step in the guide.

Remove the ledger device, unplug it, plug it back in, enter pin, open BTCP app.

**Comment by florianfink** [comment]
My Nano S is "awake" and unlocked, still get the error message.

**Comment by sulmone** [comment]
I’ll take a look at the code on that fix from upstream tonight. It seems like the ledger firmware update might have made the electrum connection a bit unstable.

**Comment by boyweiser** [comment]
Hi
when i first create a new wallet with hardware wallet option, they was 2 ledger appear, first one did not work. made error exception. The second one let me get in Electrum but with a exception :Invalid sequence error. I press Ok. then i transfer all my BTCP in my ledger. Everything confirm fine. But now i test to send back a little, and i got Exception: Invalid sequence. And nothing ask me to sign on the Ledger.
 It's a bit scary to be honest.

**Comment by sulmone** [comment]
Can you try the 1.1.1 version?

I set up a new hardware wallet from scratch and transferred my balance to it with no issues.

**Comment by jriggity** [comment]
Yes I am having the same issue and I downloaded the 1.1.0

**Comment by benthecarman** [comment]
I can store coins on 1.1.1 but I cannot recover forked coins from it

**Comment by Artanisx** [comment]
I'll try 1.1.1 as soon as possible (probably on Monday) and will report back results :)

**Comment by jriggity** [comment]
I actually got it to work took quite a few times but I got it

**Comment by boyweiser** [comment]
The new update from Chris Fix this issue. Thank you mate. keep the good work

**Comment by Osolong2** [comment]
Chris,
You are the MAN!!

**Comment by Artanisx** [comment]
I can confirm, now it works! Thanks :)

**Comment by drunkenclam** [comment]
But spending from Segwit adresses still doesn't work, correct?

**Comment by Artanisx** [comment]
Haven't tried yet.

**Comment by jpartz** [comment]
Hi i cant figure out where to find version 1.1.1 to fix this problem.

**Comment by drunkenclam** [comment]
https://github.com/BTCPrivate/electrum-btcp/releases
