### ISSUE TITLE
failed to execute script electrum-btcp

### ISSUE THREAD

**Issue by Vonwelz** [BTCPrivate/electrum-btcp#6]
Hi i'm trying to claim my BTCP.

When I try to sweep via new wallet>private keys>sweep  with a clean install I get  his error: 

https://ibb.co/gOd6YS

When I do clean install and choose option import BTCP addresses or private keys I get this error: "failed to execute script electrum-btcp"

System info:
- Running Windows 10 (tried on 2 seperate computers)
- ZCL is on electrum wallet 1.0.0 since 28-01-2018

Help :'(

**Comment by ch4ot1c** [comment]
#7
