### ISSUE TITLE
SERVER CLOSED?

### ISSUE THREAD

**Issue by nolteman** [BTCPrivate/electrum-btcp#60]
NOW WHAT
![image](https://user-images.githubusercontent.com/6262110/39102225-75dc8388-4667-11e8-8be5-ef2063fb18b8.png)

the last 2 days I have been seeing Pending shares Increasing and decreasing without changes in the pending and final balance

http://pool.btcprivate.org/dashboard.html to my personal wallet I've been mining 40 hours straight  without getting a single coin, HELP

**Comment by interbiznw** [comment]
Whats your mining address?

**Comment by nolteman** [comment]
don't worry, it's fixed, as I'm new, all must be a scandal 😂

2018-04-22 22:48 GMT-05:00 J62 <notifications@github.com>:
