### ISSUE TITLE
"Not connected" problem

### ISSUE THREAD

**Issue by belskikh** [BTCPrivate/electrum-btcp#61]
I can't connect to electrum btcp servers
There is "Not connected" message in the bottom left corner of the GUI.
The server address is electrum.btcprivate.org, port is 5222.

How can I establish connection?

**Comment by ifeedumass** [comment]
Same error. imho problem is caused by Roskomnadzor. What about wallet safety with using free proxy?

**Comment by belskikh** [comment]
Yeah, think so too. What proxy should I use. I tried several, but still have no connection

**Comment by mikhailivanovic** [comment]
Same issue here, any recommendations?

**Comment by ifeedumass** [comment]
Guys, working on other PC with other internet provider. Maybe only PC, maybe provider...

**Comment by ifeedumass** [comment]
Balance opened, but blocks cant synchronize. Tryed proxies, but wallet disconnect at syncronizing moment...
How can we transfer coins to other wallet?

**Comment by izoomrud** [comment]
Wallet does not work, how fix it? 
not connected

**Comment by ifeedumass** [comment]
Only proxy...Tried like 10 proxy, but disconnect alltime. Try more and u will connect! 
https://yadi.sk/i/fqw3GdHF3Uqc2W

proxy can find here https://hidemy.name/ru/proxy-list/?type=45#list

**Comment by dogking08** [comment]
still not working
