### ISSUE TITLE
BUG - Electrum wallet

### ISSUE THREAD

**Issue by nolteman** [BTCPrivate/electrum-btcp#78]
Help tags with errors in the Electrum Wallet

1 Official website 
https://electrum.org/#home
That is a **BITCOIN** ELECTRUM WALLET, NOT ELECTRUM BTCP WALLET

2 Documentation
http://docs.electrum.org/en/latest/
That is Documentation for **BITCOIN** ELECTRUM WALLET, NOT THE ELECTRUM BTCP WALLET

3 Report BUG
![image](https://user-images.githubusercontent.com/6262110/39962457-f47baf7e-5603-11e8-99d2-dbf2d76af1bd.png)
Should we report to the **BITCOIN** GITHUB the problems of **BITCOIN PRIVATE**?

I have just been insulted for reporting a Bitcoin Private WALLET problem in the **BITCOIN** Electrum forum. I JUST FOLLOWED THE LINK OF THE **ELECTRUM**  **BITCOIN PRIVATE**  WALLET.
It's stupid that BITCOIN and **BITCOIN PRIVATE** have a wallet called electrum, but even more stupid that the support links take me to **BITCOIN** forums INSTEAD OF THE **BITCOIN PRIVATE** forums. 

CHANGE THE NAME OF THE **BTCP** WALLET.

**Comment by sulmone** [comment]
Sorry about that - we will fix that screen.
