### ISSUE TITLE
Missing BTCP

### ISSUE THREAD

**Issue by someone94873** [BTCPrivate/electrum-btcp#8]
Hi there,
I just downloaded the btcp wallet, imported private key and only half of my private are there.  I only used one key the whole time with my zcl wallet and all of my zcl were 100% in the wallet before the snapshot.  It seems like this is a bug of some sort.  When I look at the transaction history on my zcl wallet and then compare it to the transaction history on my new btcp wallet there is one difference.  I think this is the problem.  I do not know how to fix this and I did everything properly.  

Any ideas?

**Comment by exxonrcg** [comment]
Hi, 
I encountered this too.
Can you try importing the private key in electrum? ANd then looking at the movement of BTCP.

In my case I saw there was a prior transfer dated Feb.22 removing half of my BTCP.
I have no ID what the heck it is. Main net only launched March 2! 

Transaction ID: d339eed3320a3d5f7ae337b2e7caf7b49a4ead0d8e55da8d78b7e327b6619d33

Anyone have ideas?

**Comment by someone94873** [comment]
I already imported the private zcl key into the electrum wallet for btcp.  

I have a similar case.  I sent some zcl out of my wallet to exchange and then back to wallet.  Funny thing is those coins are in my btcp and the coins I had in there since the 27th are not.  If you look at both wallets transaction history there is a mistake on the btcp one in which they took out double the amount when I transferred them back and forth from the exchange.  

We need help from the dev team, I believe this is a bug issue.  I know I did everything correctly.

**Comment by exxonrcg** [comment]
this solution worked from me
https://www.reddit.com/r/BitcoinPrivate/comments/81v40s/possible_solution_zero_btcp_balance_coins_appear/

It looks like some of the BTCP amount was credited to another address that is normally not hidden / not used in electrum. Exporting and importing ALL keys should help find the other coin amounts.

**Comment by someone94873** [comment]
Yoooo! Thank you so much it worked.  Good look!  Just needed to paste all of the addresses for some reason even though I only used one. :)
