### ISSUE TITLE
Electrum does not show one of two BTC addresses contained on ledger

### ISSUE THREAD

**Issue by SteffenIvanhoe** [BTCPrivate/electrum-btcp#81]
A friend of mine has a (non-segwit) account on his ledger with 2 BTC addresses containing BTC as of the time of the hard fork (28.2.18) and still today. Both addresses belong to the same account. The Electrum wallet for BTCP does only show one of the two addresses. The other one is not shown and therefore he has no access to his BTCP.

Is there a way to convert a public BTC address to the corresponding BTCP address? This would help to check whether the BTCP explorer at least shows the right content.

**Comment by SteffenIvanhoe** [comment]
I have found a website (findmycoins.ninja) which shows me the respective BTCP address and there I can see that the blockchain correctly holds the BTCP. The error seems to be with the Electrum wallet which does not show the address although it belongs to the displayed HD wallet.

**Comment by sulmone** [comment]
You probably need to generate more addresses. Either that or your coins are in a change address.

**Comment by sulmone** [comment]
Check here in the gap limit section and the way to generate more addresses in the console:
http://docs.electrum.org/en/latest/faq.html

**Comment by SteffenIvanhoe** [comment]
The address which I miss is a change address, resulting from an outbound transfer. I can generate a lot of new addresses but this does not make visible the missing address. Anyway the one address which is visible was one that I created later then the missing one. If addresses get generated in a given order based on the public master key then the Electrum wallet should have seen it before the one which is visible because it got created earlier!? Or is there some other algorithm with change addresses? Then how will it be either possible to access them without a transaction history?

**Comment by SteffenIvanhoe** [comment]
I found the solution!

I can force Electrum wallet to generate change addresses instead of receive addresses! That finally generated the missed address!

Use the following command in the console: 
  print(wallet.create_new_address(True))
Repeat it until the address pops up (balance changes). Or use a loop:
  for x in range(0, 100): print(wallet.create_new_address(True))
